// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyMOnkjAu_BcPpMGVF5ok2BQ5cgiYruKo',
    appId: '1:132979348220:web:5fd1a10f1cb96cc5e0fd79',
    messagingSenderId: '132979348220',
    projectId: 'auth-a0776',
    authDomain: 'auth-a0776.firebaseapp.com',
    storageBucket: 'auth-a0776.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB78nCDSTA2vD2DNBv9CLAhhwLHm9jOyM0',
    appId: '1:132979348220:android:ff19ad5290880bdce0fd79',
    messagingSenderId: '132979348220',
    projectId: 'auth-a0776',
    storageBucket: 'auth-a0776.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9pxTugxvQdRLhnF_rtmSKqdP6qhsPdT4',
    appId: '1:132979348220:ios:ebc0921e7a45958be0fd79',
    messagingSenderId: '132979348220',
    projectId: 'auth-a0776',
    storageBucket: 'auth-a0776.appspot.com',
    iosClientId: '132979348220-sshasm8mibjkanv35025br8n1fqli332.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginScreen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9pxTugxvQdRLhnF_rtmSKqdP6qhsPdT4',
    appId: '1:132979348220:ios:ebc0921e7a45958be0fd79',
    messagingSenderId: '132979348220',
    projectId: 'auth-a0776',
    storageBucket: 'auth-a0776.appspot.com',
    iosClientId: '132979348220-sshasm8mibjkanv35025br8n1fqli332.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginScreen',
  );
}
